### ISSUE TITLE
[BUG] example.txt included in cold package

### ISSUE THREAD

**Issue by liam-teale** [LemLib/LemLib#116]
#### Expected Behavior
example.txt should not be included in the cold package

#### Observed Behavior
example.txt is in the cold package

#### Steps to Reproduce
compile the program, use your favorite decompiler to view example.txt in the LemLib.a binary

#### Environment
 - LemLib Version: 0.5.0-rc1 and newer
 - PROS Kernel Version: 3.8.0
 - PROS CLI Version: 3.4.3
 - Additional Templates: None

#### Additional Information
New users are confused when their program does not compile if they have `example.txt` in the `static` folder.

#### Potential Fix
Modify asset.mk so it will add assets from the `cold_static` folder to the cold package, and add assets from the `static` folder into the hot package

**Comment by ABUCKY0** [comment]
@SizzinSeal This can be closed
