### ISSUE TITLE
[FEATURE] Doxygen workflow

### ISSUE THREAD

**Issue by liam-teale** [LemLib/LemLib#12]
### Requested Feature
When a new release has been pushed, the docs should be automatically updated to reflect new changes and version increments. This includes tutorials, doxygen documentation, and javadocs at the start of the source files.

### Benefits
- Easier maintenance

**Comment by Exortions** [comment]
I'll work on this later today.

Had some issues with the Doxygen workflow last night, so hopefully I can get them ironed out today.
I'll also have a V5 brain to test new features tonight, so will be able to test other features.

**Comment by liam-teale** [comment]
Doxygen macros can be used to expand things like the project version (e.x expanding LemLib@VER.zip to LemLib@0.4.2.zip), so only a single line has to be changed in the doxyfile

**Comment by Exortions** [comment]
Re-opening to address other issues

**Comment by liam-teale** [comment]
Doxygen does not run on push to master branch. It deploys the pages but does not update
