### ISSUE TITLE
[BUG] Tutorial Docs Image Paths are Wrong

### ISSUE THREAD

**Issue by Jackman3323** [LemLib/LemLib#144]
#### Expected Behavior
Images to be displayed

#### Observed Behavior
Picture icon is displayed, its looking for the pictures in tutorials/assets/[filename], when in reality the assets folder is at the same level as the tutorials folder.

#### Steps to Reproduce
Open the tutorials (at least number 2) on github

#### Environment
Master branch

**Comment by liam-teale** [comment]
The paths are correct. If you are referring to how the images don't show up when viewing the raw markdown files, its a limitation of GitHub. GitHub does not allow for relative image paths
