### ISSUE TITLE
[FEATURE] Drive Motor Velocity Controller

### ISSUE THREAD

**Issue by liam-teale** [LemLib/LemLib#4]
### Problem
Currently, drivetrain motors are controlled directly by the motion algorithms simply by controlling their voltage. This reduces the effectiveness of the motion algorithms, and makes velocity units confusing

### Proposed Solution
The chassis class should have velocity controllers for drivetrain motors. This way, motion algorithms can simply request the drivetrain to move at a specified speed (e.g 6 in/s)

**Comment by ItzSt0rmz** [comment]
Dibs when I get some time available

**Comment by ItzSt0rmz** [comment]
I'm also going to include a turnAtSpeed function because its in a similar vein

**Comment by liam-teale** [comment]
Closing, as this is now up to motions to implement
