### ISSUE TITLE
[BUG] Tracking wheels prioritized before IMU for heading

### ISSUE THREAD

**Issue by meisZWFLZ** [LemLib/LemLib#69]
#### Expected Behavior
If IMU is present, then it should be used. 

#### Observed Behavior
IMU is only used if there are no pairs of tracking wheels.

#### Environment
 - LemLib Version: Every version with the chassis class
    - [From its creation](https://github.com/LemLib/LemLib/blob/de68ebad6401e5b15aefb1b9b44e910ecb2c7c6b/src/lemlib/chassis/odom.cpp#L125)
    - [To today](https://github.com/LemLib/LemLib/blob/cff7f33a22418385b8052e26c6d64b6b53858991/src/lemlib/chassis/odom.cpp#L156) 
 - PROS Kernel Version: N/A
 - PROS CLI Version: N/A

#### Additional Information
The inertial's one purpose is to provide heading data. If it is present in the sensors struct, that means the user wants the imu to be used. Therefore it should be of the highest priority.
I'd be happy to submit a pull request to fix this, although could I create it on the v0.4.7 branch so that a new patch can be released, fixing this bug?

**Comment by liam-teale** [comment]
There is a workaround available: Just don't pass both tracking wheels to the drivetrain struct. This makes no difference to odom accuracy since it only uses 1 tracking wheel regardless of how many are passed to it. This will be fixed in the next v0.5.0 beta release
